apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customstatefulsets.example.com
spec:
  group: example.com
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              application:
                type: object
                properties:
                  name:
                    type: string
                  replicas:
                    type: integer
                    default: 1
                  # NEW FIELD ADDED HERE
                  resourceRequirements:
                    type: object
                    properties:
                      cpu:
                        type: string
                        default: "100m"
                      memory:
                        type: string
                        default: "128Mi"
                    default:
                      cpu: "100m"
                    memory: "128Mi"
                required:
                - name
            required:
            - application
          status:
            type: object
            properties:
              phase:
                type: string
        required:
        - spec
  scope: Namespaced
  names:
    plural: customstatefulsets
    singular: customstatefulset
    kind: CustomStatefulSet
