apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-server-side-diff
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test-server-side-diff
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-server-side-diff
    spec:
      containers:
        - name: idle
          image: spurin/idle:latest
          ports:
            - containerPort: 3000
              name: http
