apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-server-side-diff
  labels:
    environment: production
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test-server-side-diff
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-server-side-diff
        environment: production
    spec:
      containers:
        - name: idle
          image: spurin/idle:latest
          ports:
            - containerPort: 9872
              name: http
