apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-server-side-diff-daemon
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test-server-side-diff
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-server-side-diff
    spec:
      containers:
      - name: idle-daemon
        image: spurin/idle:latest
        ports:
        - containerPort: 9871
          name: http
