apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: example-prometheus-rule
  namespace: monitoring
spec:
  groups:
    - name: example-rules
      rules:
        - alert: HighMemoryUsage
          expr: process_memory_bytes > 50000000
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: High Memory Usage
        - alert: HighCPUUsage
          expr: process_cpu_seconds_total > 0.75
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: High CPU Usage
    - name: additional-rules
      rules:
        - alert: NetworkTrafficHigh
          expr: rate(container_network_receive_bytes_total[10m]) > 1000000
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: High Network Traffic
