apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ssd-removal
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
    - SkipDryRunOnMissingResource=true
  source:
    path: guestbook
    repoURL: https://github.com/pjiang-dev/argocd-example-apps
    targetRevision: HEAD
