apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: apps:argoproj.io/Application:argocd/ssd-test
    argocd.argoproj.io/refreshtest: normal
    argocd.argoproj.io/skip-reconcile: "true"
  name: ssd-test
  namespace: argocd
spec:
  destination:
    namespace: kustomize-guestbook
    server: https://kubernetes.default.svc
  project: default
  sourceHydrator:
    drySource:
      path: guestbook
      repoURL: https://github.com/pjiang-dev/argocd-example-apps
      targetRevision: HEAD
    syncSource:
      path: guestbook
      targetBranch: master
