apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: appofapps:argoproj.io/Application:argocd/ssd-test
    argocd.argoproj.io/compare-options: ServerSideDiff=true
  name: ssd-test
  namespace: argocd
spec:
  destination:
    namespace: kustomize-guestbook
    server: https://kubernetes.default.svc
  project: default
  sourceHydrator:
    drySource:
      repoURL: https://github.com/pjiang-dev/argocd-example-apps
      targetRevision: HEAD
    syncSource:
      path: apps
      targetBranch: master
