apiVersion: v1
kind: ConfigMap
metadata:
  name: test-app-config
  namespace: default
data:
  nginx.conf: |
    user nginx;
    worker_processes 1;
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 80;
        location / {
          return 200 "Hello from test-app\n";
        }
      }
    }

