apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-app-name-56442febe66700c603f02402e5d5ce63
  namespace: default
data:
  postgres.conf: |
    # PostgreSQL configuration
    max_connections = 100
    shared_buffers = 128MB
