apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-name
  namespace: default
  labels:
    app: app-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-name
  template:
    metadata:
      labels:
        app: app-name
      annotations:
        instrumentation.opentelemetry.io/inject-java: 'true'
    spec:
      serviceAccountName: app-name
      containers:
      - name: app-name
        image: nginx:latest
        ports:
        - name: grpc
          containerPort: 6565
        - name: metrics
          containerPort: 9113
        resources:
          limits:
            cpu: '1'
            memory: '4Gi'
          requests:
            cpu: '1'
            memory: '4Gi'
        volumeMounts:
        - name: postgres
          mountPath: /app/conf/postgres.conf
          subPath: postgres.conf
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 15
          failureThreshold: 5
          successThreshold: 1
          timeoutSeconds: 5
          httpGet:
            port: 9113
            path: /health/liveness
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 15
          failureThreshold: 5
          successThreshold: 1
          timeoutSeconds: 5
          httpGet:
            port: 9113
            path: /health/readiness
      volumes:
      - name: postgres
        configMap:
          name: postgres-app-name-56442febe66700c603f02402e5d5ce63
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: '25%'
      maxUnavailable: '25%'

