apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: aws-load-balancer-webhook
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/managed-by: cert-manager
  annotations:
    cert-manager.io/inject-ca-from: kube-system/aws-load-balancer-tls
webhooks:
- name: vingress.elbv2.k8s.aws
  clientConfig:
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /validate-networking-v1-ingress
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBekNDQWV1Z0F3SUJBZ0lKQUw4MjJuMlhUU1VqTUEwR0NTcUdTSWIzRFFFQkN3VUFNQkV4RHpBTkJnTlYKQkFNTUJrTkJJSEp2YjNRd0hoY05Nakl3TWpFeE1EVXhOekEyV2hjTk16SXdNakE0TURVeE56QTJXakFSTVE4dwpEUVlEVlFRRERBWkRRU0J5YjI5ME1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCnExZzVzVGozRmh1Y1pneUVHZkhMOEFUeERMZDNGUXJlcTJwYUk3MGYwajZPeHZZbFhYRjUwZTdCd05kL2pxSjYKb1VQVnpwM20xSmJ5SzNjY2JXZVJORzhTZ1lxRkVWN3MyWjBPckd3Zm1jSUtxdVZqaldrQTQ5NDdXV2M1eXZYegpRbHJ1NGpvcnJLUlBpUjk5VmFOTUtmYTd6VHppcmFLSkpkMDQyL0tsdmFlNmp0ZWhSQWNzVWdUZmVoZFgyV3ByCkh0TCs2cVdFNUJ2NDRQdjdXMGx4eUVMQjZrWjMxVVhjb1Y5UjBlc0VaZS9LZll3OFNsN0I3ZEJvWUdUMXRFMkoKVFNYbE1nNkJRbkVRMWFNdm5KWnRIVWYyWFJVQjNNVmlkU3B4L0lZWjdwSG81QllqSThoR0liQ1JQeUpIRFhmMApYT2cxNHVJRWpHb0VWdEpQVGNNdGNRSURBUUFCbzFNd1VUQWRCZ05WSFE0RUZnUVVpWnQ3R3dPcDdVdnRucnF5ClpWTDkwZHM1ZDZJZ0ZnUVVpWnQ3R3dPcDdVdnRucnF5WlZMOTBkczVkNkl3RGdZRFZSMFFBd2NHQTFVZEVBRUEKd2pHZ0ZrQ0FnWUJnTEFGbGZaRVdFalYzUlJrSlBjSGdHZFNjU1h0NXdpcGY4Ukh3bURFd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBQVhDOHF0Mll4NGVxcUlqdlR4Q1V1dUNWeUFsL09CVTB0OGVvU0JQb1dxZzFEc2xsZnViCm8vZlJtZjkrMVlBZWJnYzJuaTN3U3RZWmMyVTNHdWh3eGJsUU5SSHhlZDFaV2g5cTgvR0p1WDdyTktDcVF3d00KTWZLaU9iR09MZWJGd3ByTGhYVllVQlpMYk9WVVRMTDFKeGMxQnpUZHNsckJwU0Y3QTl5Ym1XRGZJNmowYjdIRQpQRHhPeVQ1K0ZWQjVZK3I2VXdyTW1Vc29pOHFaVUpuV3EwRHZuMjlJZnNjRkNXSGVNZVJIRGhLaGJtNjJzekczCnEzZGZWWm0yZ0ZHZzMvUmJmRVlxZjArN2dvam5KRlpHZUFrcUdhSU01QXdUSERFZjBpeU5kSWZkR3l3M0RJaUIKNUJZVTFLZ2I0N2RaOVdmbFFVOGdOWTZ4TU1zVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["networking.k8s.io"]
    apiVersions: ["v1"]
    resources: ["ingresses"]
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  failurePolicy: Fail
  namespaceSelector: {}
- name: vtargetgroupbinding.elbv2.k8s.aws
  clientConfig:
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /validate-elbv2-k8s-aws-v1beta1-targetgroupbinding
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBekNDQWV1Z0F3SUJBZ0lKQUw4MjJuMlhUU1VqTUEwR0NTcUdTSWIzRFFFQkN3VUFNQkV4RHpBTkJnTlYKQkFNTUJrTkJJSEp2YjNRd0hoY05Nakl3TWpFeE1EVXhOekEyV2hjTk16SXdNakE0TURVeE56QTJXakFSTVE4dwpEUVlEVlFRRERBWkRRU0J5YjI5ME1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCnExZzVzVGozRmh1Y1pneUVHZkhMOEFUeERMZDNGUXJlcTJwYUk3MGYwajZPeHZZbFhYRjUwZTdCd05kL2pxSjYKb1VQVnpwM20xSmJ5SzNjY2JXZVJORzhTZ1lxRkVWN3MyWjBPckd3Zm1jSUtxdVZqaldrQTQ5NDdXV2M1eXZYegpRbHJ1NGpvcnJLUlBpUjk5VmFOTUtmYTd6VHppcmFLSkpkMDQyL0tsdmFlNmp0ZWhSQWNzVWdUZmVoZFgyV3ByCkh0TCs2cVdFNUJ2NDRQdjdXMGx4eUVMQjZrWjMxVVhjb1Y5UjBlc0VaZS9LZll3OFNsN0I3ZEJvWUdUMXRFMkoKVFNYbE1nNkJRbkVRMWFNdm5KWnRIVWYyWFJVQjNNVmlkU3B4L0lZWjdwSG81QllqSThoR0liQ1JQeUpIRFhmMApYT2cxNHVJRWpHb0VWdEpQVGNNdGNRSURBUUFCbzFNd1VUQWRCZ05WSFE0RUZnUVVpWnQ3R3dPcDdVdnRucnF5ClpWTDkwZHM1ZDZJZ0ZnUVVpWnQ3R3dPcDdVdnRucnF5WlZMOTBkczVkNkl3RGdZRFZSMFFBd2NHQTFVZEVBRUEKd2pHZ0ZrQ0FnWUJnTEFGbGZaRVdFalYzUlJrSlBjSGdHZFNjU1h0NXdpcGY4Ukh3bURFd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBQVhDOHF0Mll4NGVxcUlqdlR4Q1V1dUNWeUFsL09CVTB0OGVvU0JQb1dxZzFEc2xsZnViCm8vZlJtZjkrMVlBZWJnYzJuaTN3U3RZWmMyVTNHdWh3eGJsUU5SSHhlZDFaV2g5cTgvR0p1WDdyTktDcVF3d00KTWZLaU9iR09MZWJGd3ByTGhYVllVQlpMYk9WVVRMTDFKeGMxQnpUZHNsckJwU0Y3QTl5Ym1XRGZJNmowYjdIRQpQRHhPeVQ1K0ZWQjVZK3I2VXdyTW1Vc29pOHFaVUpuV3EwRHZuMjlJZnNjRkNXSGVNZVJIRGhLaGJtNjJzekczCnEzZGZWWm0yZ0ZHZzMvUmJmRVlxZjArN2dvam5KRlpHZUFrcUdhSU01QXdUSERFZjBpeU5kSWZkR3l3M0RJaUIKNUJZVTFLZ2I0N2RaOVdmbFFVOGdOWTZ4TU1zVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["elbv2.k8s.aws"]
    apiVersions: ["v1beta1"]
    resources: ["targetgroupbindings"]
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  failurePolicy: Fail
  namespaceSelector: {}
- name: vingressclassparams.elbv2.k8s.aws
  clientConfig:
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /validate-elbv2-k8s-aws-v1beta1-ingressclassparams
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBekNDQWV1Z0F3SUJBZ0lKQUw4MjJuMlhUU1VqTUEwR0NTcUdTSWIzRFFFQkN3VUFNQkV4RHpBTkJnTlYKQkFNTUJrTkJJSEp2YjNRd0hoY05Nakl3TWpFeE1EVXhOekEyV2hjTk16SXdNakE0TURVeE56QTJXakFSTVE4dwpEUVlEVlFRRERBWkRRU0J5YjI5ME1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCnExZzVzVGozRmh1Y1pneUVHZkhMOEFUeERMZDNGUXJlcTJwYUk3MGYwajZPeHZZbFhYRjUwZTdCd05kL2pxSjYKb1VQVnpwM20xSmJ5SzNjY2JXZVJORzhTZ1lxRkVWN3MyWjBPckd3Zm1jSUtxdVZqaldrQTQ5NDdXV2M1eXZYegpRbHJ1NGpvcnJLUlBpUjk5VmFOTUtmYTd6VHppcmFLSkpkMDQyL0tsdmFlNmp0ZWhSQWNzVWdUZmVoZFgyV3ByCkh0TCs2cVdFNUJ2NDRQdjdXMGx4eUVMQjZrWjMxVVhjb1Y5UjBlc0VaZS9LZll3OFNsN0I3ZEJvWUdUMXRFMkoKVFNYbE1nNkJRbkVRMWFNdm5KWnRIVWYyWFJVQjNNVmlkU3B4L0lZWjdwSG81QllqSThoR0liQ1JQeUpIRFhmMApYT2cxNHVJRWpHb0VWdEpQVGNNdGNRSURBUUFCbzFNd1VUQWRCZ05WSFE0RUZnUVVpWnQ3R3dPcDdVdnRucnF5ClpWTDkwZHM1ZDZJZ0ZnUVVpWnQ3R3dPcDdVdnRucnF5WlZMOTBkczVkNkl3RGdZRFZSMFFBd2NHQTFVZEVBRUEKd2pHZ0ZrQ0FnWUJnTEFGbGZaRVdFalYzUlJrSlBjSGdHZFNjU1h0NXdpcGY4Ukh3bURFd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBQVhDOHF0Mll4NGVxcUlqdlR4Q1V1dUNWeUFsL09CVTB0OGVvU0JQb1dxZzFEc2xsZnViCm8vZlJtZjkrMVlBZWJnYzJuaTN3U3RZWmMyVTNHdWh3eGJsUU5SSHhlZDFaV2g5cTgvR0p1WDdyTktDcVF3d00KTWZLaU9iR09MZWJGd3ByTGhYVllVQlpMYk9WVVRMTDFKeGMxQnpUZHNsckJwU0Y3QTl5Ym1XRGZJNmowYjdIRQpQRHhPeVQ1K0ZWQjVZK3I2VXdyTW1Vc29pOHFaVUpuV3EwRHZuMjlJZnNjRkNXSGVNZVJIRGhLaGJtNjJzekczCnEzZGZWWm0yZ0ZHZzMvUmJmRVlxZjArN2dvam5KRlpHZUFrcUdhSU01QXdUSERFZjBpeU5kSWZkR3l3M0RJaUIKNUJZVTFLZ2I0N2RaOVdmbFFVOGdOWTZ4TU1zVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["elbv2.k8s.aws"]
    apiVersions: ["v1beta1"]
    resources: ["ingressclassparams"]
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  failurePolicy: Fail
  namespaceSelector: {} 
