apiVersion: v1
data:
  key1: value1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"test-config","creationTimestamp":null},"data":{"key1":"value1"}}
  creationTimestamp: "2025-04-07T23:03:20Z"
  labels:
    peter-test: FROM-MUTATION-WEBHOOK
  name: test-config
  namespace: argocd
  resourceVersion: "1525020"
  uid: 33f47168-75e7-4cbd-bf93-031c3acb348e
